[package]
name = "frost-protocol"
version = "0.1.0"
edition = "2024"
description = "Finality Reliant Optimized State Transition Protocol"
license = "Apache-2.0"

[dependencies]
# Async runtime
tokio = { version = "1.36", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Types
uuid = { version = "1.7", features = ["v4", "serde"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Crypto
sha2 = "0.10"
blake2 = "0.10"

# Utilities
tracing = "0.1"
futures = "0.3"
parking_lot = "0.12.4"
